language: node_js
node_js: stable
cache:
  bundler: true
  directories:
    - node_modules
    - public

install:
  - npm install

jobs:
  include:
    - stage: Github Pages
#      allow_failure: true
      script: npm run build
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: public
        target-branch: master
        repo: $GH_REF
      env: GH_REF=be-fe/be-fe.github.io